# Generated by Django 5.2.6 on 2025-09-30 11:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/', validators=[users.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='series/', validators=[users.models.validate_image]),
        ),
    ]
