# Generated by Django 5.2.6 on 2025-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(upload_to='people/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
                ('actors', models.ManyToManyField(blank=True, related_name='acted_movies', to='movies.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_movies', to='movies.person')),
            ],
        ),
    ]
